version: "3.8"

services:
  postgresdb:
    image: postgres:15.7
    restart: unless-stopped
    container_name: ai-speech-to-text
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"