version: "3.8"

services:
  postgresdb:
    image: postgres:15.7
    restart: unless-stopped
    container_name: ai-speech-to-text
    ports:
      - 5432:5432
    volumes:
      - "postgres_db_data:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: aispeechtotext
      POSTGRES_PASSWORD: aispeechtotext
      POSTGRES_DB: aispeechtotext
      PGDATA: "/var/lib/postgresql/data/pgdata"
volumes:
  postgres_db_data: